config/routes.rb
Subtwittle::Application.routes.draw do

  match "/tweetimage" => "tweetimage#index"
  match "/tweetimage/:twitter_handle" => "tweetimage#show", :as => :twitter_user

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/tweetimage_controller.rb
require 'open-uri'
require 'tweet_filter'

class TweetimageController < ApplicationController
  
  def index
    redirect_to "/tweetimage/#{params[:twitter_handle]}"
  end
  
  def show
    @handle = params[:twitter_handle]

    # fetch tweets
    twitter_api_url = "https://api.twitter.com/1/statuses/user_timeline.json?screen_name=#{@handle}&count=10"
    begin
      tweets = JSON.parse(open(twitter_api_url).read).map {|t| t['text'] }
    rescue OpenURI::HTTPError => err
      tweets = []
      flash[:error] = case err.message
        when '401 Unauthorized'
          'Twitter user not does not permit their tweets to be accessed by outside services.'
        else
          'Something went wrong!'
      end
    end
    
    @tweets = {}
    tweets.each do |tweet|
      google_image_api_url = "https://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=#{URI.escape(filter_tweet(tweet))}"
      images = JSON.parse(open(google_image_api_url).read)
      if images['responseData']['results'].size > 0
        @tweets[tweet] = images['responseData']['results'].first['tbUrl']
      end
    end
  end
  
  private
  include TweetFilter
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweetimage_helper.rb
module TweetimageHelper
end

app/views/home/index.html.erb
<%= form_tag twitter_user_path, :method => :get do %>
  <%= label_tag :user, 'Twitter Handle:' %>
  <%= text_field_tag :twitter_handle %>
  
  <%= submit_tag 'Visualize Tweets'%>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweet Visualizer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <h1>Tweet Visualizer</h1>
  
  <% if flash[:error] %><p class="error"><%= flash[:error] %></p><% end %>

<%= yield %>

</body>
</html>

app/views/tweetimage/show.html.erb
<p>Showing <span class="tweet_count"><%= @tweets.size %></span> most recent tweets from <span class="handle"><%= @handle %></span>.</p>

<ul id="tweet_list">
<% @tweets.each do |tweet, image_url| %>
  <li>
    <span class="image"><%= image_tag image_url %></span>
    <span class="tweet"><%= tweet %></span>
  </li>
<% end %>
</ul>